### Array slicing

In [7]:
import numpy as np
a = np.array([6, 7, 8])
a

array([6, 7, 8])

In [8]:
a[0:2], a[-1]

(array([6, 7]), 8)

In [13]:
a2d = np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])
a2d

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [14]:
a2d[1, 2]

3

In [16]:
a2d[0:2, 2]

array([8, 3])

In [18]:
a2d[-1]

array([9, 3, 2])

In [19]:
a2d[-1, 0:2]

array([9, 3])

In [20]:
a2d[:, 1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [21]:
for row in a2d:
    print (row)

[6 7 8]
[1 2 3]
[9 3 2]


In [22]:
for cell in a2d.flat: # Convert it to 1 dimensional array
    print (cell)

6
7
8
1
2
3
9
3
2


### Array Stacking

In [23]:
a = np.arange(6).reshape(3, 2)
b = np.arange(6, 12).reshape(3, 2)

In [24]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [27]:
np.vstack((a, b)) # Seems a is put on b vertically. Note (a, b) is a tuple

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [28]:
np.hstack((a, b)) # Seems a is put before b horizontally

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [30]:
a = np.arange(30).reshape(2, 15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [31]:
result = np.hsplit(a, 3) # Seems a is cut horizontally in 3 equal sizes
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [34]:
result = np.vsplit(a, 2) # Seems a is cut horizontally in 3 equal sizes
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

### Indexing with boolean arrays

In [35]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
a[b] # Cool way to get all elements greater tahn 4 from an nd array.

array([ 5,  6,  7,  8,  9, 10, 11])

In [41]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])