### Iterate numpy array using nditer

In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Using normal for loop iteration

In [3]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


#### For loop with flatten

In [5]:
for cell in a.flat:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


# nditer

#### C style ordering

In [6]:
for x in np.nditer(a, order='C'): # C style - row by row
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


#### Fortan style ordering

In [7]:
for x in np.nditer(a, order='F'): # Fortran style - column by column
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


### external_loop

In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
for x in np.nditer(a, flags=['external_loop'],order='F'): # Entire column in one iteration
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


## Modify array values while iterating

In [13]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [14]:
a

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

## Iterate two broadcastable arrays concurrently

In [15]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [16]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
16 3
81 3
256 7
625 7
1296 7
2401 7
4096 11
6561 11
10000 11
14641 11
